### PR TITLE
Babashka support

### LINKED ISSUE #39: Support babashka?
Would be lovely to have one canonical GH action that supports doing cached installs of different Clojure CLI tools. 

There's a few `setup-babashka` projects, but why not just integrate it here as well, seems like it would be similar to other tools?

### PR DESCRIPTION
**Pull request by zharinov**
Closes #39

### CODE REVIEW

**Comment by zharinov** [comment]
Example run: https://github.com/zharinov/setup-clojure/runs/5644382707?check_suite_focus=true

**Comment by zharinov** [comment]
Okay, this PR is ready for review/merge for now, I believe

**Review by DeLaGuardo — APPROVED** [review]
LGTM

**Comment by zharinov** [comment]
By the way, thank you @just-sultanov for your code on which this implementation is based. I appreciate it.

**Pull request merged**
